language: generic
sudo: required
dist: trusty
services:
- docker
matrix:
  include:
  - env: ARCH=x86_64 ARCH_CMD=linux64
    os: linux
  - os: osx
before_install: bin/ci prepare_system
install: bin/ci prepare_build
script:
- bin/ci with_build_env 'make'
after_success:
- mv ./authoritah authoritah-$TRAVIS_OS_NAME
notifications:
  slack:
    secure: VI1gD1I8chUxWLQUAPm+Iea5U7wm/6Gzf6KOAtN9/NcnhaXSkIKFvPe7bm3GPXVSnJmpGcK6bIEblybm35p2QpfXnyQYYNf0GKGRrwDL7k9g0XKcjNshO2TM7D0ZVNYQTs0leGypQU4PdS0xhg3SkIigz6UcLeadBIp8OXQ3U/Afh72i2r0x3UgYJ4xkiBwEdKiZ38o4OuJtVcWmBPMv/clEIj5JUkoSCV4JL5K1Ij16Iu8KLWAhHOvjyRmC8NHvX754hf6ZygJlCNdyAqxwmr8NHh2bn2ujwbcBl8z+eS6XorEesgtSgxTgkiUqKnHvxAP2/gzRMLmEEoKpVu/68OvOstnwtqClelj9tBtzRp1uaylhacM1sw3rmbrEjl7dQRPzt50yzb6T+H/YPcnYcOAHPEGT6wuVgKeyVCWmHaHxgu75Tf6nWc0RI7dyKphkVGjGueoB/opsfxeN9itRwQCHujQ0nu1wsNQa8n/Ersd5Q6cGXctvQ+w+XYY1b+/reIwnIy0/ty5bkYAkZC3bS5p7Suxo6QFicuysqaHlylXoa1xV97w7rYCF2xpJYQSPfB5SvQqkOIvmLNkNqIQ8WQ3YeIviKOx0hdJ9f6ysye9+G1EnvlpRjpafEtFWu/UBJqM+3kx2yUYiq0pQ/M+u2VleU3iCa+KV2de9oBjGoIQ=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gwqXvIo8faPtNtDt3zGIZBbSNBFHJCKG7DG38PHsJ2KfZc6mg0d9dLq+nabNTEazuVPbvGbQDqRRbjcc+aAZlKmNRQKTy3N4VMfQDaOiMLlSKAZBfpaB5SVqt2nKztkSbNiERN/8i5P0qqYFN15bo1nNBqEvD5Rf9zwLx1oPZ6Zri1UUk/MyjQ383vPL8VXVVXND752x3nk33GHIAejWCRl7VMKlGW/q0kef8yPyenolHJQea/wNnD9+K5GTltjeV8MyF9mV0znj+QKaJhaeyXay+zhjkV7Cv62n7+yW0waJGudXhw5tCDgETkyOvfQ72TXAGhs3Q4f2ZcKSBW9GQsIW4nju3gfXpJZHVQ6de+OobkC2nvV6af9kQ0YJYM+YeYij65eldrJbNbK6AvppL3iCm+gqeLwW3EJTeMz9WLG3oDCYzki61TLYG5uF6nvo5zyDaEZ7OeBvVrlIIs3osjW0YpuUph4w3mydu15I+AFAsjKqKccGIZQOK+dBOw++cXXW8t9GHOx+qQhTzKxuQaIKjcG4kjClU3LD8vQ4L/BvektEt9JFq8DVpwfEgI//G0+wsHlb+Eve2XTVo0VMXY18kyGgsrcMiuSQ+v99N6c1nZGXvyHRZ3zR6ZL9WKCUvYvrHETBwXNAay5ghAPtfeYmkGHUjOndCG5w3bR36IQ=
  file: 
    - authoritah-$TRAVIS_OS_NAME
  on:
    tags: true
